### PR TITLE
feat(repo): :construction: Add searchresult story

### PR DESCRIPTION
**Pull request by narangodapasan**
Channel search result card
result card

### CODE REVIEW

**Review by chxru — CHANGES_REQUESTED** [review]
Nice job on components. I see three separate components here
1. Search result card
2. Search result card container
3. Card on left side

They should be three separate stories. Split them to different stories so we can import them individually in the app

**Comment by narangodapasan** [comment]
> ### Doctor profile card,

image

> ### Result card,
image

> ### Result card container,
image

> ### All 3 responsive compoents together, expected view,
image

**Review by chxru — APPROVED** [review]

**Comment by chxru** [comment]
@narangodaNPP scope repo is used for changes in repository (ie nx related changes). Use UI scope for changes in UI components

**Comment by narangodapasan** [comment]
> scope repo is used for changes in repository (ie nx related changes). Use UI scope for changes in UI components
understood

**Pull request merged**
